title: Hangout Server Help Page
description: Help page for the Hangout Server
baseurl: "/"
url: "https://help.hs.axthedev.xyz"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Main Server":
    - "https://discord.gg/AenCQBMKfT"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs